c-------------------------------------------------------------------------------------------------c
      program project_euler_44
c-------------------------------------------------------------------------------------------------c
c                                                                                                 c
c  Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal        c
c  numbers are:                                                                                   c
c                                                                                                 c
c  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...                                                    c
c                                                                                                 c
c  It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is   c
c  not pentagonal.                                                                                c
c                                                                                                 c
c  Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is          c
c  pentagonal and D = |Pk − Pj| is minimised; what is the value of D?                             c
c                                                                                                 c
c-------------------------------------------------------------------------------------------------c
      implicit none
      include 'euler.inc'

c parameters used in this program only
      integer*8 pents(10000), min_diff, n1, pent1, pent1_test, n2, pent2, pent2_test
      integer*8 k_index, j_index

c initialize the min_diff and the list of pentagonal numbers
      min_diff = 10e9
      do x1=1,10000
        pents(x1) = x1*(3*x1-1)/2
      enddo
      
      do x1=2,10000
        do x2=1,x1-1
c check to see if the difference is a pentagon
          pent1 = pents(x1) - pents(x2)
          n1 = int((1+sqrt(1+24*dble(pent1)))/6)
          pent1_test = n1*(3*n1-1)/2
          if (pent1.eq.pent1_test) then
            
c check to see if the sum is a pentagon
            pent2 = pents(x1) + pents(x2)
            n2 = int((1+sqrt(1+24*dble(pent2)))/6)
            pent2_test = n2*(3*n2-1)/2
            if (pent2.eq.pent2_test) then
              if (pent1.lt.min_diff) then
                min_diff = pent1
                k_index = x1
                j_index = x2
              endif
            endif
          endif
        enddo
      enddo
            
      write(*,*) 'The pair of pentagonal numbers is indices ',k_index,' and ',j_index
      write(*,*) 'The min value of D is ',min_diff
      
      end