c-------------------------------------------------------------------------------------------------c
      program project_euler_2
c-------------------------------------------------------------------------------------------------c
c                                                                                                 c
c  Project Euler Problem 2:                                                                       c
c                                                                                                 c
c  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By      c
c  starting with 1 and 2, the first 10 terms will be:                                             c
c                                                                                                 c
c  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                                         c
c                                                                                                 c
c  By considering the terms in the Fibonacci sequence whose values do not exceed four million,    c
c  find the sum of the even-valued terms.                                                         c  
c                                                                                                 c
c-------------------------------------------------------------------------------------------------c
      implicit none
      include 'euler.inc'

c parameters used in this program only
      integer*8 sum, max_fib, fib_n, fib_number

c initialize the sum, the start of the fibonacci sequance and the max value for the fibonacci number
      sum = 0
c      fib_n = 1
      fib_n = 3
      fib_number = fibonacci(fib_n)
      max_fib = 4000000

c make sure the fibonacci number is less than the max value      
      do while(fib_number.lt.max_fib)

c if it is even then add to the sum
        if (is_multiple(fib_number,2)) then
          sum = sum + fib_number
        endif

c go to the next fibonacci number
c        fib_n = fib_n + 1
        fib_n = fib_n + 3
        fib_number = fibonacci(fib_n)

      enddo        

      write(*,*) sum
      
      end